// joditConfig.js
const globalJoditConfig = {
    readonly: false,
    placeholder: 'Start typing your blog post...',
    uploader: {
        insertImageAsBase64URI: true,
    },
    iframe: true,
    iframeStyle:
        'html{margin: 0px;}body{padding: 10px;background: transparent;color: #000;position: relative;z-index: 2;user-select: auto;margin: 0px;overflow: hidden;}body:after{content: "";clear: both;display: block}',
    askBeforePasteHTML: true,
    width: 'auto',
    height: 'auto',
    minHeight: '500',
    allowResizeX: true,
    editSrc: true,
    buttons: [
        'source',
        '|',
        'bold',
        'strikethrough',
        'underline',
        'italic',
        '|',
        'ul',
        'ol',
        '|',
        'outdent',
        'indent',
        '|',
        'font',
        'fontsize',
        'brush',
        'paragraph',
        '|',
        'image',
        'video',
        'table',
        'link',
        '|',
        'align',
        'undo',
        'redo',
        '|',
        'hr',
        'eraser',
        'copyformat',
        '|',
        'symbol',
        'fullsize',
        'print',
        'about',
    ],
    buttonsXS: [
        'bold',
        'image',
        '|',
        'brush',
        'paragraph',
        '|',
        'align',
        '|',
        'undo',
        'redo',
        '|',
        'eraser',
        'dots',
    ],
};

export default globalJoditConfig;
